# Generated by Django 5.2.7 on 2025-12-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author_category_book_description_book_total_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_count',
        ),
    ]
